import traceback
import streamlit as st
import datetime
import sys

from agent.agentic_workflow import GraphBuilder
from State.DBState import AgentState

# from exception.exceptions import TradingBotException

st.set_page_config(
    page_title="🌍 Smart DB Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("🌍 Smart DB Agentic Application")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat history
st.header(
    "How can I help you for your database queries? Let me know what you want to do with your database."
)

# Chat input box at bottom
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input(
        "User Input",
        placeholder="e.g. Show me all customers from California",
    )
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:

        with st.spinner("Bot is thinking..."):

            graph = GraphBuilder()

            state = AgentState(
                user_query=user_input
            )

            result = graph.invoke(state)

            # Handle different return types
            if isinstance(result, AgentState):
                answer = (
                    result.sql_query
                    or result.identified_intent
                    or str(result)
                )

            elif isinstance(result, dict):

                if "sql_query" in result:
                    answer = result["sql_query"]

                elif "answer" in result:
                    answer = result["answer"]

                elif "messages" in result:
                    last_message = result["messages"][-1]
                    answer = getattr(last_message, "content", str(last_message))

                else:
                    answer = str(result)

            else:
                answer = str(result)

            markdown_content = f"""# 🌍 AI Database Query Result

# **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}
# **Created by:** Atriyo's Database Agent

---

{answer}

---

*This database query result was generated by AI. Please verify all information before using it.*
"""

            st.markdown(markdown_content)


    except Exception:
        st.code(traceback.format_exc())