from pydantic import BaseModel, Field
from typing import Any, Dict, List, Optional, Annotated

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

class AgentState(BaseModel):
    """
    Shared state passed between LangGraph nodes.
    """

        ########################################################
    # LangGraph Conversation State
    ########################################################

    messages: Annotated[
        List[BaseMessage],
        add_messages,
    ] = Field(
        default_factory=list,
        description="Conversation history stored by LangGraph."
    )

    

    project_id: Optional[str] = Field(
        default=None,
        description="Current project id."
    )

    conversation_id: Optional[str] = Field(
        default=None,
        description="Current conversation id."
    )

    thread_id: Optional[str] = Field(
        default=None,
        description="LangGraph persistence thread id."
    )

    connection_name: Optional[str] = Field(
    default=None,
    description="Connection name registered in              ConnectionManager."
    )

    # Original user input
    user_query: str = Field(
        ...,
        description="Natural language query provided by the user."
    )

    # Intent identified by the Intent Detection node
    identified_intent: Optional[str] = Field(
        default=None,
        description="High-level intent of the user (SELECT, INSERT, UPDATE, DELETE, ANALYTICS, etc.)."
    )

    db_connection: Any = Field(
        default=None,
        description="Active database connection."
    )

    # Retrieved database schema relevant to the query
    schema: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Relevant schema context retrieved using RAG."
    )

    # SQL generated by the LLM
    sql_query: Optional[str] = Field(
        default=None,
        description="Generated SQL query."
    )

    # Confidence score assigned to generated SQL
    query_confidence_score: float = Field(
        default=0.0,
        ge=0.0,
        le=100.0,
        description="Confidence score (0-100) for generated SQL."
    )

    # Maximum refinement attempts allowed
    max_iteration: int = Field(
        default=5,
        ge=1,
        description="Maximum number of SQL generation iterations."
    )

    # Current iteration count
    used_iteration: int = Field(
        default=0,
        ge=0,
        description="Number of iterations used so far."
    )

    # Whether the generated SQL is considered dangerous
    is_dangerous: bool = Field(
        default=False,
        description="True if the SQL contains potentially destructive operations."
    )

    # Actual SQL operation type
    sql_query_intent: Optional[str] = Field(
        default=None,
        description="Actual SQL operation (SELECT, INSERT, UPDATE, DELETE, ALTER, DROP, etc.)."
    )

    # SQL generated for demo database (optional)
    demo_db_implementation: Optional[str] = Field(
        default=None,
        description="Equivalent SQL/query executed on demo database."
    )

    # User approval before execution
    user_approval: bool = Field(
        default=False,
        description="Whether the user approved execution of the generated SQL."
    )