from typing import Any, Dict, List, Optional, Annotated

from pydantic import BaseModel, Field

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class AgentState(BaseModel):
    """
    Shared state across the LangGraph workflow.

    Only values that need to persist across multiple nodes
    should be stored here.
    """

    ########################################################
    # LangGraph Conversation State
    ########################################################

    messages: Annotated[
        List[BaseMessage],
        add_messages,
    ] = Field(
        default_factory=list,
        description="Conversation history maintained by LangGraph.",
    )

    ########################################################
    # Session Metadata
    ########################################################

    project_id: Optional[str] = Field(
        default=None, description="Current project identifier."
    )

    conversation_id: Optional[str] = Field(
        default=None, description="Current conversation identifier."
    )

    thread_id: Optional[str] = Field(
        default=None, description="LangGraph persistence thread id."
    )

    ########################################################
    # Database Information
    ########################################################

    connection_name: Optional[str] = Field(
        default=None, description="Registered database connection name."
    )

    db_connection: Any = Field(
        default=None, description="Active database connection object."
    )

    database_config: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Serializable database configuration used to reconnect.",
    )

    ########################################################
    # Current Query State
    ########################################################

    user_input: Optional[str] = Field(
        default=None, description="Latest natural language input from the user."
    )

    identified_intent: Optional[str] = Field(
        default=None, description="Intent identified from the user input."
    )

    schema_context: Optional[Dict[str, Any]] = Field(
        default=None, description="Relevant schema retrieved from Vector Database."
    )

    generated_sql_query: Optional[str] = Field(
        default=None, description="SQL query generated by the LLM."
    )

    query_confidence: Optional[float] = Field(
        default=None, description="LLM confidence score for the generated query."
    )

    query_risk_level: Optional[str] = Field(
        default=None, description="Risk level assigned to the generated query."
    )

    requires_approval: Optional[bool] = Field(
        default=None, description="Whether the generated query needs user approval."
    )

    query_reasoning: Optional[str] = Field(
        default=None, description="Short explanation of why the query was generated."
    )

    query_type: Optional[str] = Field(
        default=None, description="Query category such as read or write."
    )

    affected_tables: List[str] = Field(
        default_factory=list,
        description="Tables affected or referenced by the generated query.",
    )

    execution_result: Optional[Any] = Field(
        default=None, description="Result returned after executing the SQL query."
    )

    demo_result: Optional[Dict[str, Any]] = Field(
        default=None, description="Demo application's before/after preview."
    )

    ########################################################
    # Workflow State
    ########################################################

    current_node: Optional[str] = Field(
        default=None, description="Current workflow node."
    )

    workflow_status: Optional[str] = Field(
        default=None, description="Current workflow status."
    )

    approval: Optional[bool] = Field(
        default=None, description="User approval after demo preview."
    )

    # Agentic refinement state.
    critic_status: Optional[str] = None
    critic_reasoning: Optional[str] = None
    investigation_query: Optional[str] = None
    investigation_result: Optional[Any] = None
    investigation_evidence: Optional[str] = None
    refinement_count: int = 0
    max_refinements: int = 2
